config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'

  resources :cocktails
  resources :ingredients
  resources :doses

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates_presence_of :name
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @ingredients = Ingredient.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :picture)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def destroy
    dose = Dose.find(params[:id])
    @cocktail = dose.cocktail
    @ingredient = dose.ingredient
    dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  def create
    dose = Dose.new
    dose.cocktail = Cocktail.find(params[:dose][:cocktail_id])
    dose.ingredient = Ingredient.find(params[:dose][:ingredient_id])
    dose.amount = params[:dose][:amount].to_f
    if dose.save
      redirect_to cocktail_path(dose.cocktail)
    else
      render template: "ingredients_controller/show"
    end
  end



  private

  # def cocktail_params
  #   params.require(:cocktail).permit(:name)
  # end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredient_path(@ingredient)
    else
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredient_path(@ingredient)
    else
      render :edit
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<%= render 'shared/form' %>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6"><h1>Crazy cocktails!</h1></div>
    <div class="col-xs-6"><%= link_to "(go to ingredients)", ingredients_path, {class: "btn btn-primary"} %></div>
  </div>
</div>

<% @cocktails.each do |cocktail| %>
  <div class="container">
    <div class="row">
      <h2><%= cocktail.name.capitalize %></h2>
      <div class="col-xs-6">
        <%= image_tag cocktail.picture.url(:thumb) if cocktail.picture.present? %>
      </div>

      <div class="col-xs-6">
        <p><% cocktail.ingredients.each_with_index do |ingredient, i| %>
          <% if i==0 %>
            <%= ingredient.name.capitalize %>,
          <% elsif i == cocktail.ingredients.length - 1 %>
            <%= ingredient.name %>.
          <% else %>
            <%= ingredient.name %>,
          <% end %>
        <% end %></p>

        <%= link_to "View", cocktail_path(cocktail) %>
        <%= link_to "Delete?", cocktail_path(cocktail),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>
<% end %>

<h2>Add a cocktail</h2>
<%= simple_form_for(@cocktail, html: { multipart: true, class: 'form-inline' }) do |f| %>
  <%= f.input :name %>
  <%= f.file_field :picture %>
  <%= f.submit %>
<% end %>

app/views/cocktails/new.html.erb
<%= bootstrap_form_for(@cocktail) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create Cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name.capitalize %></h1>

<%= image_tag @cocktail.picture.url if @cocktail.picture.present? %>

<h2>Ingredients</h2>

<% @cocktail.ingredients.each do |ingredient| %>
  <p><%= ingredient.name.capitalize %>: <%= @cocktail.doses.where(ingredient: ingredient).first.amount %> doses
    <%= link_to (image_tag ("delete.png"), {class: "img-circle", id: "logo", height: "15px"}),
      dose_path(@cocktail.doses.where(ingredient: ingredient).first),
      method: :delete
    %>
  <p>
<% end %>

<h3>Add ingredient</h3>

<%= simple_form_for(Dose.new, url: doses_path) do |f| %>
  <%= f.input :amount %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <%= f.hidden_field :cocktail_id, value: params[:id] %>
  <%= f.submit %>
<% end %>


<%= link_to "back",
  cocktails_path,
  {class: "btn btn-primary"} %>

app/views/ingredients/edit.html.erb
<%= render 'shared/form' %>

app/views/ingredients/index.html.erb
<h1>Our cocktails include the craziest ingredients ...</h1>
<p><%= link_to "(go to cocktail list)", cocktails_path, {class: "btn btn-primary"} %></p>

<% @ingredients.each do |ingredient| %>
  <h2><%= ingredient.name.capitalize %></h2>
  <h4>Find it in ...</h4>

  <p><% ingredient.cocktails.each_with_index do |cocktail, i| %>
    <% if i == ingredient.cocktails.length - 1 %>
      <%= cocktail.name.capitalize %>...
    <% elsif i == 0 %>
      <%= cocktail.name.capitalize %>,
    <% else %>
      <%= cocktail.name.capitalize %>,
    <% end %>
  <% end %></p>

  <%= link_to "View", ingredient_path(ingredient) %>
  <%= link_to "Delete?", ingredient_path(ingredient),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

<% end %>

app/views/ingredients/new.html.erb
<%= bootstrap_form_for(@ingredient) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create Cocktail", class: "btn btn-primary" %>
<% end %>

app/views/ingredients/show.html.erb
<h2><%= @ingredient.name.capitalize %></h2>

<h1>Belongs to:</h1>

<% @ingredient.cocktails.each do |cocktail| %>
  <p>Rating: <%= cocktail.name %>  (<%= ingredient.cocktail.dose %> dose(s)<p>
<% end %>

<%#= bootstrap_form_for [@restaurant, @review] do |f| %>
  <%#= f.text_field :content %>
  <%#= f.text_field :rating %>
  <%#= f.submit %>
<%# end %>

<%= link_to "back",
  restaurants_path,
  {class: "btn btn-primary"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mistercocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_form.html.erb
<%= bootstrap_form_for(@restaurant) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :address %>
  <%= f.text_field :phone_number %>
  <%= f.text_field :category %>
  <%= f.select :stars, [["1 étoile", 1], ["2 étoiles", 1], ["3 étoiles", 3], ["4 étoiles", 4], ["5 étoiles", 5]] %>
  <%= f.submit "Create Restaurant", class: "btn btn-primary" %>
<% end %>